export const USER_TRANSFER = 'USER_TRANSFER';
export const USER_TRANSFER_ERROR = 'USER_TRANSFER_ERROR';
export const USER_TRANSFER_SUCCESS = 'USER_TRANSFER_SUCCESS';
export const RESET = 'RESET';
